apiVersion: v1
kind: Service
metadata:
  name: osrm-server-andorra-service
spec:
  type: NodePort
  selector:
    app: osrm-server-andorra
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
